/**
 * Regenerates the committed seed snapshot under web/public/data/.
 *
 * The site always prefers the live /api/* functions; these files are the
 * offline fallback that makes a cold or rate-limited deployment still render
 * real numbers instead of an empty shell. They are generated by running the
 * SAME handlers the deployment runs, so the fallback can never drift out of
 * schema with the live endpoint — that drift is exactly what left a 15-country
 * atlas.v1 bundle sitting behind an atlas.v2 API.
 *
 * Also snapshots the IV accrual history into api/iv_history.json, which Vercel
 * bundles into the functions and /api/status reads.
 *
 * Usage: npm run seed
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repo = resolve(root, "..");
const dataDir = resolve(root, "public", "data");
mkdirSync(dataDir, { recursive: true });

/* ---- load .env so the handlers see FRED_API_KEY, exactly like serve.mjs ---- */
{
  const envPath = resolve(repo, ".env");
  if (existsSync(envPath)) {
    for (const line of readFileSync(envPath, "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  }
  console.log(`env: FRED_API_KEY ${process.env.FRED_API_KEY ? "loaded" : "MISSING"}`);
}

/** minimal res shim so a Vercel handler can be run in-process */
function capture(handler, url) {
  return new Promise((res, rej) => {
    const chunks = [];
    const fakeRes = {
      statusCode: 200,
      setHeader() {},
      end(body) {
        try {
          res(JSON.parse(body));
        } catch (e) {
          rej(e);
        }
      },
      write(c) {
        chunks.push(c);
      },
    };
    Promise.resolve(handler({ url, method: "GET", headers: {} }, fakeRes)).catch(rej);
  });
}

const write = (name, doc) => {
  writeFileSync(resolve(dataDir, name), JSON.stringify(doc, null, 1));
  return doc;
};

/* ---- atlas -> bundle.json ---- */
try {
  const { default: atlasHandler } = await import("../api/atlas.js");
  const atlas = await capture(atlasHandler, "/api/atlas");
  if (atlas?.status !== "OK") throw new Error(atlas?.why || "atlas returned no data");
  write("bundle.json", {
    ...atlas,
    note: "Seed snapshot produced by running the live /api/atlas handler locally. The deployed site prefers the live endpoint; this file only serves a cold or rate-limited deployment.",
  });
  console.log(`bundle.json written — ${Object.keys(atlas.countries).length} markets, schema ${atlas.schema}`);
} catch (e) {
  console.error("bundle.json NOT refreshed:", e.message);
}

/* ---- status -> status.json + api/iv_history.json ---- */
try {
  const { computeStatus } = await import("../api/status.js");
  const ivPath = resolve(repo, "data", "iv_history.json");
  if (existsSync(ivPath)) {
    const iv = JSON.parse(readFileSync(ivPath, "utf8"));
    writeFileSync(resolve(root, "api", "iv_history.json"), JSON.stringify(iv, null, 1));
    const st = computeStatus(iv);
    write("status.json", st);
    const ticks = Object.fromEntries(Object.entries(iv).map(([t, d]) => [t, Object.keys(d || {}).length]));
    console.log(`iv_history.json copied to api/ (${JSON.stringify(ticks)})`);
    console.log(`status.json written — ${st.features.length} gated features`);
  } else {
    console.log("data/iv_history.json missing — Signals snapshot left as-is");
  }
} catch (e) {
  console.error("status.json NOT refreshed:", e.message);
}

/* ---- derived documents -> public/data/cache/{atlas,returns} ----
 *
 * Warm the cachedJson store for the endpoints that compute rather than merely
 * fetch. Locally WRITE_ROOT === SEED_ROOT, so calling each handler writes its
 * document straight into the committed snapshot, which vercel.json bundles
 * into the functions. Without this a cold serverless instance starts with an
 * empty /tmp and pays the full assembly cost on the first request: the
 * upstream series are already seeded, but the VAR fits and atlas alignment on
 * top of them are not, which measured 4-6.5s cold in production.
 */
try {
  const { default: returnsHandler } = await import("../api/returns.js");
  const combos = [];
  for (const market of ["us", "eu", "em", "countries"]) {
    for (const basis of ["hold", "vol"]) combos.push([market, basis]);
  }
  let warmed = 0;
  for (const [market, basis] of combos) {
    const r = await capture(returnsHandler, `/api/returns?market=${market}&basis=${basis}`);
    const book = r?.markets?.[market];
    const n = book ? (book.pure || []).length + (book.spread || []).length : 0;
    if (r?.status === "OK" && n) warmed++;
    console.log(`  returns ${market}/${basis}: ${r?.status} — ${n} assets`);
  }
  console.log(`derived returns cache warmed — ${warmed}/${combos.length} books`);
} catch (e) {
  console.error("derived returns cache NOT warmed:", e.message);
}
